server:
  port: 9910

spring:
  application:
    name: file-manage-service
  cloud:
    zookeeper:
      connect-string: 10.16.98.192:2188
      max-retries: 10
  redis:
    host: 10.13.81.190
    password: lab205wj
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.13.81.186:3306/lab_file_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lab205
    driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        min-idle: 1    #数据库连接池最小维持的连接数
        initial-size: 1   #初始化的连接数
        max-total: 10    #最大连接数

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

# ===================================================================
# 文件系统 配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.13.81.190:22122

lab-file-system:
  nginx:
    ip: 10.13.81.190
    port: 8216
  cache-time: 60
  cache-prefix: mds-file